title: Ayan Gaur
logo: /assets/img/IMG_0180.jpg
description: >
  Sophmore at UC San Diego majoring in Math & CS
  <br>
  Email: ayan.gaur@gmail.com 
  <br>
  <a>Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/ayan-gaur/">LinkedIn</a>
  <br>
  <a href="">
remote_theme: pages-themes/minimal@v0.2.0
