title: Ayan Gaur
logo: /assets/img/
description: Sophmore at UC San Diego majoring in Math & CS
<br>
  Email: ayan.gaur@gmail.com 
  <br>
  <br>
  <a>View My Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/ayan-gaur/">View My LinkedIn Profile</a>
  <br>
  <a href="">
remote_theme: pages-themes/minimal@v0.2.0
