title: Ayan Gaur
logo: assets/img/IMG_0180.jpg
description: >
  Sophmore at UC San Diego majoring in Mathematics & Computer Science
  <br>
  <br>
  <b>Email: ayan.gaur@gmail.com</b>
  <br>
  <a href="https://drive.google.com/file/d/1teDMtAYbe3HOxPKYSFXRoaXVif7T9IK2/view?usp=sharing"><b><h2>Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/ayan-gaur/">LinkedIn</a>
  </h2></b>
github: false
project: false
remote_theme: pages-themes/minimal@v0.2.0

