title: Ayan Gaur
logo: assets/img/IMG_0180.jpg
description: >
  Sophmore at UC San Diego majoring in Math & CS
  <br>
  Email: ayan.gaur@gmail.com 
  <br>
  <br>
  <a href="https://drive.google.com/file/d/1teDMtAYbe3HOxPKYSFXRoaXVif7T9IK2/view?usp=sharing">Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/ayan-gaur/">
    <img src=assets/img/LI-In-Bug.png>
  </a>
  <br>
  <a href="">
remote_theme: pages-themes/minimal@v0.2.0
