title: Ayan Gaur
logo: assets/img/IMG_0180.jpg
description: >
  Sophmore at UC San Diego majoring in Mathematics & Computer Science
  <br>
  <br>
  <b>Email: ayan.gaur@gmail.com</b>
  <br>
  <a projects/projects><b><h2>Projects</a>
  <br>
  <br>
  <a href="https://drive.google.com/file/d/1FTec5dQLAGLac3-EaZX6xEBHPhBzy2nB/view?usp=drive_link">Resume</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/ayan-gaur/">LinkedIn</a>
  <br>
  <br>
  <a href="https://github.com/ayangaur26">GitHub</a>
  </h2></b>
github: false
remote_theme: pages-themes/minimal@v0.2.0

